# Generated by Django 5.2.1 on 2025-05-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_event_type_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
